# Generated by Django 5.2.6 on 2025-11-25 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(blank=True)),
                ('last_name', models.TextField(blank=True)),
                ('email', models.TextField(blank=True)),
                ('occupation', models.TextField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('specialization', models.TextField(blank=True)),
                ('experience_years', models.TextField(blank=True)),
                ('languages', models.TextField(blank=True)),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('bio', models.TextField(blank=True)),
                ('verified', models.BooleanField(default=False)),
                ('join_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(blank=True)),
                ('last_name', models.TextField(blank=True)),
                ('email', models.TextField(blank=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True)),
                ('emergency_contact_name', models.TextField(blank=True)),
                ('emergency_contact_phone', models.TextField(blank=True)),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('insurance_provider', models.TextField(blank=True)),
                ('insurance_id', models.TextField(blank=True)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('health_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mindwell.healthprovider')),
            ],
        ),
        migrations.CreateModel(
            name='TherapyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('kids', 'Kids'), ('individual', 'Individual'), ('family', 'Family')])),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')])),
                ('start_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('health_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mindwell.healthprovider')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mindwell.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField()),
                ('session_time', models.TimeField()),
                ('duration', models.IntegerField(default=60)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no-show', 'No-Show')])),
                ('session_type', models.CharField(choices=[('message', 'Message'), ('audio', 'Audio Chat'), ('video', 'Video Chat')])),
                ('notes', models.TextField(blank=True, null=True)),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('trial', 'Trial')])),
                ('follow_up_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mindwell.patient')),
                ('therapy_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mindwell.therapyplan')),
            ],
        ),
    ]
