# Generated by Django 5.2.6 on 2025-12-04 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindwell', '0003_healthprovider_gender_healthprovider_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthprovider',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='therapy_description',
        ),
        migrations.AlterField(
            model_name='healthprovider',
            name='verified',
            field=models.BooleanField(default=True),
        ),
    ]
