# Generated by Django 5.2.6 on 2025-12-04 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindwell', '0004_remove_healthprovider_gender_remove_patient_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthprovider',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', ' Female'), ('other', ' Other')], max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', ' Female'), ('other', ' Other')], max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='therapy_description',
            field=models.TextField(blank=True),
        ),
    ]
