# Generated by Django 5.2.6 on 2025-12-09 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindwell', '0005_healthprovider_gender_patient_gender_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availability',
            options={'ordering': ['day_of_week', 'start_time'], 'verbose_name_plural': 'Availabilities'},
        ),
        migrations.AddField(
            model_name='plantype',
            name='providers',
            field=models.ManyToManyField(blank=True, related_name='supported_plan_types', to='mindwell.healthprovider'),
        ),
        migrations.AlterField(
            model_name='healthprovider',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('therapy_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='mindwell.therapyplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mindwell.healthprovider')),
                ('therapy_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_notes', to='mindwell.therapyplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
