# Generated by Django 5.2.6 on 2025-12-09 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mindwell', '0006_alter_availability_options_plantype_providers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at']},
        ),
    ]
