# Generated by Django 5.2.6 on 2025-12-09 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mindwell', '0007_alter_message_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='subject',
        ),
        migrations.DeleteModel(
            name='PatientNote',
        ),
    ]
